### ISSUE TITLE
Should not process pages with content-type equals to "application/*+xml"

### ISSUE THREAD

**Issue by niederlec** [istex/istex-web-extension#8]
This issue is almost the same as : https://github.com/istex/istex-browser-extension/commit/bf7dda036afe16b4ceb044f278d06c77455daa12#diff-989f36bb0ca710eb5fb30a41d09827a6

**Comment by niederlec** [comment]
Example of page with XML broken display : https://www.idref.fr/139753753.rdf

**Comment by kerphi** [comment]
Pour illustrer : 

Sans l'extension ça donne : 
![image](https://user-images.githubusercontent.com/328244/48437620-1e01cf80-e782-11e8-8fd6-6f2885756e16.png)

Avec l'extension ça donne : 
![image](https://user-images.githubusercontent.com/328244/48437636-307c0900-e782-11e8-9f34-8aaee4fa0941.png)

**Comment by niederlec** [comment]
j'allais clore le ticket mais tu me mets le doute...
As-tu testé la version 1.3.1 que j'ai publiée cet après-midi ?
PS : j'aime bien le choix de l'exemple ;-)

**Comment by kerphi** [comment]
Non non tu peux le fermer, j'ai ajouté les copies d'écrans de François pour montrer comment on aurait pu formuler le bug directement ici. Je ferai un petit mail demain pour y faire référence.
